# This file was generated by GoReleaser. DO NOT EDIT.
cask "straddle" do
  version "1.0.3"

  on_macos do
    on_arm do
      sha256 "4f21f4c9fb82801365bf932fb872f3ce6f2354608944fc6009038502b4868201"
      url "https://github.com/straddle-build/straddle-cli/releases/download/v#{version}/straddle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f28ea4cb0f9cc105b87f53d06971157b721b132472f4e1d50ee1eff840edf53e"
      url "https://github.com/straddle-build/straddle-cli/releases/download/v#{version}/straddle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "db1f810f3bc3cf252eaef2e15860f5475fbe7a245aaa80a33ddfdc96fa0083fc"
      url "https://github.com/straddle-build/straddle-cli/releases/download/v#{version}/straddle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eae3eda0d91b9c55fdfb7ce42d8b24cbb8c109c3fc43e3de790130ab8840b9b5"
      url "https://github.com/straddle-build/straddle-cli/releases/download/v#{version}/straddle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "straddle"
  desc "Human and agent friendly CLI for the Straddle API"
  homepage "https://github.com/straddle-build/straddle-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "straddle"

  # No zap stanza required
end
